/* eslint-disable */
// Auto-generated by @active-record-ts/active-record. Do not edit by hand.
// This file is the source of truth for the database schema; loading
// it (via `db:schema:load`) recreates the database from scratch.

import { defineSchema } from '@active-record-ts/active-record';

export const version = '20260101000002';

export default defineSchema((s) => {
  s.createTable('posts', (t) => {
    t.column('user_id', 'integer', { null: false });
    t.column('title', 'string', { null: false, limit: 255 });
    t.column('body', 'text');
    t.column('published', 'integer', { default: false });
    t.column('created_at', 'datetime', { null: false });
    t.column('updated_at', 'datetime', { null: false });
  });

  s.createTable('users', (t) => {
    t.column('name', 'string', { null: false, limit: 255 });
    t.column('email', 'string', { null: false, limit: 255 });
    t.column('created_at', 'datetime', { null: false });
    t.column('updated_at', 'datetime', { null: false });
  });
  s.addIndex('users', ['email'], { name: 'index_users_on_email', unique: true });
});
